# -*- coding: utf-8 -*-
"""advisory_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P-sIOEpYv6Gn0ulJcuAJ8FA-khnLzArT

This implements advisory agent
"""

import investor_profiles
import stock_universe
import disclosure_snippets
import numpy as np
import json
import array

RISK_PROFILES = [
{"risk_tolerance": "Conservative", "distribution_strategy": "equal-weight", "stocks_list": ["PAYBOND", "PAYGOLD", "PAYRETAIL"]},
{"risk_tolerance": "Moderate", "distribution_strategy": "equal-weight", "stocks_list": ["PAYRETAIL", "PAYINFRA", "PAYGOLD"]},
{"risk_tolerance": "Aggressive", "distribution_strategy": "equal-weight", "stocks_list": ["PAYTECH", "PAYFIN", "PAYINFRA"]}
]

# Defines the tools

def get_stock_data(ticker: str):
  return stock_universe.STOCK_UNIVERSE.get(ticker), stock_universe.MARKET_RETURN, stock_universe.RISK_FREE_RATE

def calculate_return_stock(Rm: float, Rf: float, beta: float):
  return Rf + beta * (Rm - Rf)

def calculate_return_portfolio(weights: np.array, stocks: np.array, Rm: float, Rf: float, correlation: float):
  weighted_return = 0
  for i in range(len(stocks)):
    #print(stocks[i])
    weighted_return += calculate_return_stock(Rm, Rf, stocks[i].get('beta')) * weights[i]
    #print("Current weighted return: ", weighted_return)
  return weighted_return

def calculate_variance_portfolio(weights: np.array, stocks: np.array, correlation: float):
  # Var(R_p) = Σᵢ wᵢ²σᵢ² + 2·Σ_{i<j} wᵢwⱼ·Cov(Rᵢ,Rⱼ), with Cov(Rᵢ,Rⱼ) = ρ·σᵢ·σⱼ
  # correlation ρ = 0.3 for every pair of the three tickers. Convert variance to portfolio standard deviation
  variance = 0
  # Calculate Σᵢ wᵢ²σᵢ²
  for i in range(len(stocks)):
    sigma_i = stocks[i].get('std_dev')
    variance += (weights[i]**2) * (sigma_i**2)

  # Calculate 2·Σ_{i<j} wᵢwⱼ·Cov(Rᵢ,Rⱼ)
  for i in range(len(stocks)):
    for j in range(i + 1, len(stocks)):
      sigma_i = stocks[i].get('std_dev')
      sigma_j = stocks[j].get('std_dev')
      covariance = correlation * sigma_i * sigma_j
      variance += 2 * weights[i] * weights[j] * covariance
      #print("Current variance: ", variance)
  return np.sqrt(variance)

def create_stocks_portfolio(risk_tolerance: str):
  weights = []
  stocks_arr = []
  for risk in RISK_PROFILES:
    if risk_tolerance == risk.get("risk_tolerance"):
      distribution_strategy = risk.get("distribution_strategy")
      match distribution_strategy:
          case "equal-weight":
            stocks = risk.get("stocks_list")
            number_stocks = len(stocks)
            for i in range(0, number_stocks):
              stock_data, Rm, Rf = get_stock_data(stocks[i])
              weights.append( 1 / number_stocks)
              stocks_arr.append(stock_data)
            return weights, stocks_arr, Rm, Rf, 0.3
          case _:
            return "Invalid data"

def escalate_human(volatility: float):
  return volatility > 0.20

def run_tool(name, args):
    """Dispatch a tool call and print the think/act/observe trace."""
    print(f"   ACTION     -> {name}({json.dumps(args)})")
    result = TOOLS[name](**args)
    # Convert numpy boolean to Python boolean if necessary for JSON serialization
    if isinstance(result, (np.bool_)):
        result = bool(result)
    print(f"   OBSERVATION <- {json.dumps(result)}\n")
    return result

TOOLS = {
    "create_stocks_portfolio": create_stocks_portfolio,
    "get_stock_data": get_stock_data,
    "calculate_return_stock": calculate_return_stock,
    "calculate_return_portfolio": calculate_return_portfolio,
    "calculate_variance_portfolio": calculate_variance_portfolio,
    "escalate_human": escalate_human
}

# Tool schemas the LLM can read (only used in live mode)
TOOL_SCHEMAS = [
    {"name": "get_stock_data", "description": "Get details like beta, analyst expected return std_dev for a given stock identified by its ticker",
     "input_schema": {"type": "object", "properties": {"ticker": {"type": "string"}}, "required": ["ticker"]}},
    {"name": "calculate_return_stock", "description": "Calculate returns as per CAPM formula, using Rf (risk free return), Rm (Market return), beta (Beta for the stock)",
     "input_schema": {"type": "object", "properties": {"Rm": {"type": "float"}, "Rf": {"type": "float"}, "beta": {"type": "float"}}, "required": ["Rm", "Rf", "beta"]}},
    {"name": "calculate_return_portfolio", "description": "Calculate return for the portfolio using weights (array of weights of stocks in portfolio), "
    "stocks (array of stocks in portfolio), Rm (Market return), Rf (Risk free return), correlation (correlation between stocks)",
     "input_schema": {"type": "object", "properties": {"weights": {"type": "array of float"}, "stocks": {"type": "array of float"}, "Rm": {"type": "float"}, "Rf": {"type": "float"},
                                                       "correlation": {"type": "float"}}, "required": ["weights", "stocks", "Rm", "Rf", "correlation"]}},
    {"name": "calculate_variance_portfolio", "description": "Calculate Standard deviation for the portfolio using weights (array of weights of stocks in portfolio), "
    "stocks (array of stocks in portfolio), correlation (correlation between stocks)",
     "input_schema": {"type": "object", "properties": {"weights": {"type": "array of float"}, "stocks": {"type": "array of float"}, "correlation": {"type": "float"}},
                      "required": ["weights", "stocks", "Rm", "Rf", "correlation"]}}
    ]

# Steps to follow in scripted mode
AGENT_STEPS = [
    "create_stocks_portfolio",

]

stock_data, Rm, Rf = get_stock_data("PAYBOND")
#print("Stock Data -> ", Rm, Rf, stock_data)
#print("Return for stock : ", f"{calculate_return_stock(Rm, Rf, stock_data.get('beta')):.2}")
weights = [1/3, 1/3, 1/3]
stocks= []
stock_data, Rm, Rf = get_stock_data("PAYBOND")
stocks.append(stock_data)
stock_data, Rm, Rf = get_stock_data("PAYGOLD")
stocks.append(stock_data)
stock_data, Rm, Rf = get_stock_data("PAYRETAIL")
stocks.append(stock_data)
portfolio_return = calculate_return_portfolio(weights, stocks, Rm, Rf, 0.3)
portfolio_std_dev = calculate_variance_portfolio(weights=weights, stocks=stocks, correlation=0.3)
#print("Portfolio return: ", f"{portfolio_return:.2}")
#print("Portfolio variance: ", f"{portfolio_std_dev:.2}")

"""Build the definitive pipeline below"""

#print(create_stocks_portfolio("Conservative"))

# Step 1, Read Investor profile record one by one from investor_profiles.py file
for investor in investor_profiles.INVESTOR_PROFILES:
  print("Investor id : ", investor.get("investor_id"), investor.get("risk_tolerance"))

# Step 2, Call create_stocks_portfolio passing each investor's risk_tolerance. It internally calls get_stock_data
# and returns weights, stocks_arr, Rm, Rf
  inv_weights, inv_stocks, Rm, Rf, correlation = run_tool("create_stocks_portfolio", {"risk_tolerance": investor.get("risk_tolerance")})

# Step 3, Call calculate_return_portfolio passing weights, stocks, Rm, Rf, correlation
  result_return = run_tool("calculate_return_portfolio", {"weights": inv_weights, "stocks": inv_stocks, "Rm": Rm, "Rf": Rf, "correlation": correlation })

# Step 4, Call calculate_variance_portfolio passing  weights, stocks, correlation
  result_variance = run_tool("calculate_variance_portfolio", {"weights": inv_weights, "stocks": inv_stocks, "correlation": correlation})

# Step 5, Escalate to human if volatility > 20
  escalation = run_tool("escalate_human", {"volatility": result_variance})
# Print the output
  if not escalation:
    for risk in RISK_PROFILES:
      if investor.get("risk_tolerance") == risk.get("risk_tolerance"):
        print(f"For {investor.get("risk_tolerance")} investor {investor.get("investor_id")}, we recommend an allocation across {risk.get("stocks_list")} with an expected portfolio return of {result_return:.1%} and volatility of {result_variance:.1%}")
  else:
     print(f"ESCALATED_TO_HUMAN_ADVISOR, volatility: {result_variance:.1%}")
  print("-" * 150)
